### PR TITLE
Xcode 10 Support

### PR DESCRIPTION
**Pull request by Dimentar**
Hi
This PR contains Xcode 10 support, and PromiseKit dependency update to 6.4.1

Can you also tag the previous released version to `1.0.2`
And this version to `1.1.0`
Also release to Cocoapods repo

Thanks

### CODE REVIEW

**Comment by emmekappa** [comment]
@mythz have you had the chance to look at this?

**Comment by mythz** [comment]
Thx for the PR 👍 Not able to update Cocoapods yet as it doesn't look like [PromiseKit v6.4.1](https://cocoapods.org/pods/PromiseKit) has been published to Cocoapods yet:

```
 -> ServiceStack (1.1.0)
    - ERROR | [iOS] unknown: Encountered an unknown error (CocoaPods could not find compatible versions for pod "PromiseKit":
  In Podfile:
    ServiceStack (from `/Users/demisbellot/src/ServiceStack.Swift/ServiceStack.podspec`) was resolved to 1.1.0, which depends on
      PromiseKit (= 6.4.1)
```

Only v6.4.0 which is [over 1 month old](https://github.com/mxcl/PromiseKit/releases). Going to wait till v6.4.1 is available so all dependencies are in-sync, i.e. instead of downgrading to v6.4.0.

**Comment by Dimentar** [comment]
Hi @mythz 
PromiseKit v6.4.1 has only project version change https://github.com/mxcl/PromiseKit/commit/fc5a4b9acd150a4736e4df69822a7c4d4d4e2a12
https://github.com/mxcl/PromiseKit/compare/6.4.0...6.4.1
Maybe is better to change our dependency internally to v6.4.0, no need to push new PromiseKit.framwork.
We need this pod to be released ASAP
If you agree, I'll make new PR
Thanks

**Comment by mythz** [comment]
Unfortunately still not able to publish due to:

```
Updating spec repo `master`

CocoaPods 1.6.0.beta.1 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.6.0.beta.1

Validating podspec
 -> ServiceStack (1.1.0)
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Planning build
    - NOTE  | xcodebuild:  note: Constructing build description
    - NOTE  | xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file. (in target 'App')
    - ERROR | [OSX] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.

[!] The spec did not pass validation, due to 1 error.
```

I ran it again with `--verbose` and checked in the output in [pod-push.txt](https://raw.githubusercontent.com/ServiceStack/ServiceStack.Swift/master/pod-push.txt)

The part that failed was:

```
    /var/folders/7z/k1sks9wj795dd4scg5v87j180000gn/T/CocoaPods-Lint-20180926-17865-wm7ocy-ServiceStack/Pods/Target Support Files/Pods-App/Pods-App-frameworks.sh: line 104: EXPANDED_CODE_SIGN_IDENTITY: unbound variable
    Command PhaseScriptExecution failed with a nonzero exit code
    
    ** BUILD FAILED **
    
    
    The following build commands failed:
    	PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/demisbellot/Library/Developer/Xcode/DerivedData/App-gmwsydnckhsllqbmzwmfmaqmaezy/Build/Intermediates.noindex/App.build/Release/App.build/Script-FD486AF6497A41C99C02D10C.sh
    (1 failure)
```

**Comment by Dimentar** [comment]
Hi @mythz 
I tried to update cocoapods (pre) using: `sudo gem install cocoapods --pre`, and the validation is passed.
I'm not allowed to push new versions for this pod, because the owners of this pod are team@servicestack.net.
Thanks

**Comment by mythz** [comment]
@Dimentar ok thx, I've upgraded to `cocoapods --pre` and noticed PromiseKit v4.6.1 was available, so I've [updated the dependency version to v4.6.1](https://github.com/ServiceStack/ServiceStack.Swift/commit/73908bace4de8f8bada5ee1d487b80a1be7fa107) and pushed ServiceStack 1.1.0 to https://cocoapods.org/pods/ServiceStack

**Comment by Dimentar** [comment]
This is great @mythz, thanks a lot.
👍

**Pull request merged**
