### PR TITLE
Feature/pkg manager

### PR DESCRIPTION
**Pull request by Dimentar**
- [x] Added **Cocoapods** support
- [x] Added **Carthange** support
- [x] Added **Swift Package Manager** support
- [x] Removed bundled **promise.swift**
- [x] Added **PromiseKit** dependency
- [x] Fixed Date tests (non depending from TimeZone)
- [x] Changed Folder structure (**Old** folder contains old files, can be removed because Xcode plugins are not used anymore)

### CODE REVIEW

**Comment by mythz** [comment]
Wow this is awesome thx, is there anything to do on my end to publish the packages? Or are they like Swift Package Manager and users can reference the repo directly?

**Comment by Dimentar** [comment]
Hi @mythz 
**Carthage** is like **Swift PM**, can be reverenced directly.
Even **Cocoapod** can be referenced specifying **git** through:
```
pod 'ServiceStack', '~> 1.0.0', :git => 'https://github.com/ServiceStack/ServiceStack.Swift'
```
To publish [Cocoapods](https://cocoapods.org) you must follow [this procedure](https://guides.cocoapods.org/making/getting-setup-with-trunk.html)

**Comment by mythz** [comment]
Thanks, I've decided to publish it under [ServiceStack](https://cocoapods.org/pods/ServiceStack) name, I've added instructions for each of the package managers on the home page:

https://github.com/ServiceStack/ServiceStack.Swift#install

Feel free to make any changes.

Also the pre-release v5.1.1 of ServiceStack [now on MyGet](http://docs.servicestack.net/myget) imports the `ServiceStack` module by default, e.g:

```swift
import Foundation;
import ServiceStack;
```

If you're using `swift-ref` to update your DTOs you can include it when updating your DTOs by updating the `DefaultImports` option to:

```swift
/*Options:
...

DefaultImports: Foundation,ServiceStack
*/
```

**Comment by Dimentar** [comment]
Awesome 👍 
I was thinking about **ServiceStack** name too, no reason why didn't done it.
I can even rename the project name to mirror the same name of dependencies.
More will do later.

Yes, I'm using 

> DefaultImports: Foundation,ServiceStack

PS: 
> import Foundation;
import ServiceStack;

Swift doesn't need anymore semicolons.

**Comment by mythz** [comment]
Thanks for the pointer, [removed in this commit](https://github.com/ServiceStack/ServiceStack/commit/99fab78d639078158b72daa3af68373a0e1c1ada).

**Pull request merged**
